CREATE TABLE TBL_SCHOOL(
	SCHOOL_NUMBER NUMBER,
	SCHOOL_NAME VARCHAR(1000),
	CONSTRAINT PK_SCHOOL PRIMARY KEY(SCHOOL_NUMBER)
);

DROP TABLE TBL_STUDENT;

CREATE TABLE TBL_STUDENT(
	STUDENT_NUMBER NUMBER,
	STUDENT_NAME VARCHAR2(1000),
	STUDENT_AGE NUMBER,
	SCHOOL_NUMBER NUMBER,
	CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NUMBER),
	CONSTRAINT FK_STUDENT FOREIGN KEY(SCHOOL_NUMBER) REFERENCES TBL_SCHOOL(SCHOOL_NUMBER)
);


-- 학교 테이블에 학교 정보 넣기
INSERT INTO TBL_SCHOOL VALUES (1, 'DBMS 고등학교');
INSERT INTO TBL_SCHOOL VALUES (2, 'JAVA 고등학교');
INSERT INTO TBL_SCHOOL VALUES (3, '웹표준 고등학교');

SELECT * FROM TBL_SCHOOL;

-- 학생 테이블에 학생 정보 넣기
--INSERT INTO TBL_STUDENT VALUES(1, '짱구', 17, 5); -- 오류발생!! FK인 SCHOOL_NUMBER에 존재하지 않는 값을 저장하려고함
INSERT INTO TBL_STUDENT VALUES(1, '짱구', 17, 1);
INSERT INTO TBL_STUDENT VALUES(2, '철수', 17, 1);
INSERT INTO TBL_STUDENT VALUES(3, '유리', 18, 2);
INSERT INTO TBL_STUDENT VALUES(4, '훈이', 18, 3);

SELECT * FROM TBL_STUDENT;

-- UK : 다른 제약조건 설정과 거의 동일하여 UNIQUE 고유한 값을 가지는 컬럼
-- PK와 UK의 차이 : UK는 NULL을 허용한다, 즉 값을 넣지 않아도 된다

DROP TABLE TBL_STUDENT;

CREATE TABLE TBL_STUDENT( 
	-- 학생번호		NUMBER		PK설정까지
	-- 학생 아이디		ID			UK설정
	-- 학생 이름		NAME
	-- 전공			MAJOR
	-- 성별 			GENDER CHAR(1) 
	STUDENT_NUMBER NUMBER CONSTRAINT PK_STUDENT PRIMARY KEY, 
	STUDENT_ID VARCHAR2(1000) CONSTRAINT UK_STUDENT UNIQUE, -- UNIQUE는 KEY를 붙이지 않음
	STUDENT_NAME VARCHAR2(1000),
	STUDENT_MAJOR VARCHAR2(1000),
--	STUDENT_GENDER CHAR(1), -- 'M', 'W'만 저장할 것이므로 고정크기 1로 한다
	STUDENT_GENDER CHAR(1) DEFAULT 'W' NOT NULL 
	CONSTRAINT BAN_CHAR CHECK(STUDENT_GENDER = 'M' OR STUDENT_GENDER = 'W')
	-- DEFAULT 'W' 는 데이터가 들어오지 않으면 무조건 'W'값이 기본으로 들어간다
	-- 디폴트값을 'W'로 설정했으니 NULL값을 강제로 막아주는게 좋을 것이다
	-- 이럴 때 사용하는 것이 NOT NULL이라는 제약조건이다
	-- 마지막으로 이 컬럼에 'M' 또는 'W'만 들어오게 하는 제약조건을 걸어줘야한다
	-- 저장되려는 값이 'M', 'W' 인지 검사해야한다(체크 CHECK)
);

SELECT * FROM TBL_STUDENT;

DROP TABLE TBL_STUDENT;

-- 각 컬럼별 값 넣기
INSERT INTO TBL_STUDENT VALUES(1, 'AA', '김철수', '컴공', 'M');
--INSERT INTO TBL_STUDENT VALUES(2, 'AA', '신짱구', '컴공', 'M'); --오류  ID는 UK
INSERT INTO TBL_STUDENT VALUES(2, 'BB', '신짱구', '컴공', 'M');
INSERT INTO TBL_STUDENT VALUES(3, 'CC', '신유리', '컴공', 'W');
INSERT INTO TBL_STUDENT (STUDENT_NUMBER, STUDENT_ID, STUDENT_NAME, STUDENT_MAJOR)
	VALUES(4, 'DD', '김영희', '컴공');
-- 성별을 생략하면 디폴트 값인 W가 들어간다
--INSERT INTO TBL_STUDENT VALUES(4, 'DD', '김영희', '컴공', 'D'); -- 오류 GENDER는 CHECK 제약조건이 있음

SELECT * FROM TBL_STUDENT;

CREATE TABLE TBL_FLOWER( 
	FLOWER_NAME VARCHAR2(1000),
	FLOWER_COLOR VARCHAR2(1000),
	FLOWER_PRICE NUMBER,
	CONSTRAINT PK_FLOWER PRIMARY KEY(FLOWER_NAME, FLOWER_COLOR) 
);

-- 데이터 저장
INSERT INTO TBL_FLOWER VALUES ('해바라기', '빨강', 5000);
INSERT INTO TBL_FLOWER VALUES ('해바라기', '노랑', 5000);
INSERT INTO TBL_FLOWER VALUES ('튤립', '노랑', 9000);
INSERT INTO TBL_FLOWER VALUES ('튤립', '빨강', 9000);
INSERT INTO TBL_FLOWER VALUES ('해바라기', '노랑', 50000); -- 오류 조합키 2개의 컬럼이 모두 일치함


SELECT * FROM TBL_FLOWER;




