--CREATE TABLE TBL_PHONE(
--	PHONE_NUMBER NUMBER : PRIMARY KEY
--	PHONE_COLOR : VARCHAR2(1000) 
--	PHONE_SIZE : NUMBER
--	PHONE_PRICE : NUMBER
--	PHONE_PRODUCTION_DATE : DATE
--	PHONE_SALE : NUMBER
--
--CREATE TABLE TBL_CASE(
--	CASE_NUMBER : NUMBER : PRIMARY KEY
--	CASE_COLOR : VARCHAR2(1000) 
--	CASE_PRICE : NUMBER
--	PHONE_NUMBER : NUMBER : FOREIGN KEY

CREATE TABLE TBL_PHONE(
	PHONE_NUMBER NUMBER CONSTRAINT PK_PHONE_NUMBER PRIMARY KEY,
	PHONE_COLOR VARCHAR2(1000) ,
	PHONE_SIZE NUMBER,
	PHONE_PRICE NUMBER,
	PHONE_PRODUCTION_DATE DATE,
	PHONE_SALE NUMBER
	);

CREATE TABLE TBL_CASE(
	CASE_NUMBER NUMBER CONSTRAINT PK_CASE_NUMBER PRIMARY KEY,
	CASE_COLOR VARCHAR2(1000) ,
	CASE_PRICE NUMBER,
	PHONE_NUMBER NUMBER	,
	CONSTRAINT FK_PHONE_NUMBER FOREIGN KEY(PHONE_NUMBER) REFERENCES TBL_PHONE(PHONE_NUMBER)
);

SELECT * FROM TBL_PHONE tp ; --부모테이블
SELECT * FROM TBL_CASE tc ; --자식테이븜
--항산 부모테이블에 데이터가 먼저 들어가야한다(자식테이블이 부모테이블의 값을 참조하기 때문에)

INSERT INTO TBL_PHONE (PHONE_NUMBER,PHONE_COLOR,PHONE_SIZE,PHONE_PRICE,PHONE_SALE,PHONE_PRODUCTION_DATE)
VALUES (001,'black', 1, 120,10,sysdate-10);

INSERT INTO TBL_PHONE (PHONE_NUMBER,PHONE_COLOR,PHONE_SIZE,PHONE_PRICE,PHONE_SALE,PHONE_PRODUCTION_DATE)
VALUES (002,'black', 1, 120,20,TO_DATE('2023-05-05'));

SELECT * FROM TBL_PHONE tp ;

INSERT INTO TBL_CASE VALUES (101,'WHITE',5,003);
INSERT INTO TBL_CASE VALUES (101,'WHITE',5,001);
INSERT INTO TBL_CASE VALUES (102,'WHITE',5,002);

SELECT * FROM TBL_CAse;

--부모의값 수정
UPDATE TBL_PHONE 
SET PHONE_NUMBER = 003
WHERE PHONE_NUMBER = 002;

--부모의 값을 변경하때 자식에서 
--1. 자식테이블에서 참조중인값을 다른 값으로 변경한다
--2. 자식테이블에서 참조중인값을 NULL값으로 변경한다

--1. 참조중인값을 NULL
UPDATE TBL_CASE 
SET PHONE_NUMBER  = NULL 
WHERE CAse_number=101;

UPDATE TBL_PHONE  
SET PHONE_NUMBER  = 003
WHERE PHONE_NUMBER = 001;

SELECT *FROM TBL_PHONE tp ;
SELECT *FROM TBL_CASEtp ;

UPDATE TBL_CASE  
SET PHONE_NUMBER  = 3 --
WHERE PHONE_NUMBER = 105;
UPDATE TBL_CASE  
SET PHONE_NUMBER  =  --
WHERE case_NUMBER = 102;

UPDATE TBL_phone
SET PHONE_NUMBER  = 20
WHERE PHONE_NUMBER = 2;

INSERT  INTO TBL_PHONE VALUES (010, 'BLUE',2,80,sysdate,10);

UPDATE TBL_CASE 
SET PHONE_NUMBER = 010
WHERE CASE_NUMBER =3;
 


--5시 40분까지 만들기
--도서관에서 회원의 정보와 책의 정보가 필요하다.
--회원의 정보는 회원번호, 이름, 나이, 핸드폰 번호, 주소가 필요하고
--책의 정보는 도서번호, 책이름, 장르가 필요하다.
--단, 장르는 인문학, 추리, IT, 로맨스
--한 명의 회원은 여러권의 책을 빌릴 수 있다.
--테이블 명 MEMBER, BOOK
--
--2.개념적 설계
--	회원 : 회원번호 , 이름, 나이, 핸드폰번호, 주소
--	책 : 도서번호, 책이름, 장르	
--
--3. 논리적 설계(제약조건)
--	회원		책
--	회원번호(PK)	도서번호(PK)
--	이름		책이름
--	나이		장르
--	핸드폰번호		회원번호(FK)
--	주소
--	
--4. 물리적 설계(실제타입)
--
--CREATE TABLE TBL_MEMBER(
--	MEMBER_NUMBER NUMBER : PRIMARY KEY
--	MEMBER_NAME VARCHAR2(1000)
--	MEMBER_AGE NUMBER
--	MEMBER_PHONE VARCHAR2(1000)
--	MEMBER_ADDRESS VARCHAR2(1000)
--	
--
--CREATE TABLE TBL_BOOK(
--	BOOK_NUMBER  NUMBER : PRIMARY KEY
--	BOOK_NAME VARCHAR2(1000) 
--	BOOK_TYPE VARCHAR2(1000)
--	MEMBER_NUMBER NUMBER : FOREIGN KEY
--
--
--5.구현
DROP TABLE TBL_MEMBER ;

CREATE TABLE TBL_MEMBER(
	MEMBER_NUMBER NUMBER,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_AGE NUMBER,
	MEMBER_PHONE_NUMBER VARCHAR2(1000),
	MEMBER_ADDRESS VARCHAR2(1000),
	CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NUMBER)
	);


CREATE TABLE TBL_BOOK(
	BOOK_NUMBER  NUMBER,
	BOOK_NAME VARCHAR2(1000)NOT NULL, 
	BOOK_CATEGORY VARCHAR2(1000),
	MEMBER_NUMBER NUMBER ,
	CONSTRAINT PK_BOOK PRIMARY KEY(BOOK_NUMBER),
	CONSTRAINT FK_BOOK FOREIGN KEY(MEMBER_NUMBER) REFERENCES TBL_MEMBER(MEMBER_NUMBER),
	CONSTRAINT CHECK_CATEGORY 
	