CREATE TABLE TBL_USER(
	USER_NAME VARCHAR2(1000),
	USER_AGE NUMBER
);

-- 테이블명 수정
ALTER TABLE TBL_USER RENAME TO TBL_MY_USER;

-- 컬럼추가 
ALTER TABLE TBL_MY_USER ADD(USER_GENDER CHAR(4));

-- 컬럼명 수정
ALTER TABLE TBL_MY_USER RENAME COLUMN USER_NAME TO USER_NICKNAME;

-- 컬럼 삭제 
ALTER TABLE TBL_MY_USER DROP COLUMN USER_GENDER;

-- 컬럼타입 수정
ALTER TABLE TBL_MY_USER MODIFY(USER_AGE VARCHAR2(500));

SELECT * FROM TBL_MY_USER;


-- A, 20
-- B, 20
INSERT INTO TBL_MY_USER(USER_NICKNAME, USER_AGE) VALUES ('A', 20);
INSERT INTO TBL_MY_USER(USER_NICKNAME, USER_AGE) VALUES ('B', 20);

TRUNCATE TABLE TBL_MY_USER;

SELECT * FROM TBL_MY_USER;

DROP TABLE TBL_MY_USER;
/*
[실습]
자동차 테이블 생성 TBL_CAR
- 자동차 번호		숫자 CAR_NUMBER
- 자동차 이름  	문자 NAME
- 자동차 브랜드  	문자 BRAND
- 출시 날짜   		날짜 RELEASE_DATE
- 색상			문자 COLOR
- 가격			숫자 PRICE
*/
CREATE TABLE TBL_CAR(
	CAR_NUMBER NUMBER,
	CAR_NAME VARCHAR2(1000),
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(1000),
	CAR_PRICE NUMBER
);

ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(CAR_NUMBER);
-- ALTER TABLE TBL_CAR : 테이블을 수정하겠다 TBL_CAR 테이블
-- ADD : 추가한다
-- CONSTRAINT : 제약조건
-- PK_CAR : 제약조건 이름
-- PRIMARY KEY(CAR_NUMBER) : PK라는 제약조건을 CAR_NUMBER 컬럼에

ALTER TABLE TBL_CAR DROP CONSTRAINT PK_CAR;
-- 제약조건을 삭제할 때는 DROP CONSTRAINT 제약조건이름만 지정한다


DROP TABLE TBL_CAR;

CREATE TABLE TBL_CAR(
	CAR_NUMBER NUMBER PRIMARY KEY,
	CAR_NAME VARCHAR2(1000),
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(1000),
	CAR_PRICE NUMBER
);

ALTER TABLE TBL_CAR DROP CONSTRAINT SYS_C006998;

CREATE TABLE TBL_CAR(
	CAR_NUMBER NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_NAME VARCHAR2(1000),
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(1000),
	CAR_PRICE NUMBER
);


--[실습] PK를 가진 테이블에 값 넣기
-- 상품(PRODUCT) 테이블 생성
-- 제약조건 PK 설정
-- 상품번호 PK_PRODUCT
-- 이름
-- 가격

CREATE TABLE TBL_PRODUCT(
	PRODUCT_NUMBER NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(1000),
	PRODUCT_PRICE NUMBER
);

-- PRODUCT 테이블에 데이터 저장 안되는 것이 있다면 주석 처리 후 왜 안되는지 작성
-- 1, '아이패드 에어', 790000
-- 2, '갤럭시 워치', 300000
-- 1, '삼성갤럭시', 1000000
-- NULL, '갤럭시탭', 300000
INSERT INTO TBL_PRODUCT VALUES (1, '아이패드 에어', 790000);
INSERT INTO TBL_PRODUCT VALUES (2, '갤럭시 워치', 300000);
INSERT INTO TBL_PRODUCT VALUES (3, '삼성갤럭시', 7900000); -- PK 중복 허용하지 않음
INSERT INTO TBL_PRODUCT VALUES (4, '갤럭시탭', 7900000); -- PK NULL을 허용하지 않음

SELECT * FROM TBL_PRODUCT;


-- 주문테이블 생성
-- TBL_ORDER 테이블에 주문번호 PK로 설정, 상품번호를 FK로 설정
DROP TABLE TBL_PRODUCT;

CREATE TABLE TBL_ORDER(
	ORDER_ID NUMBER, --PK
	PRODUCT_NUMBER NUMBER,
	ORDER_DATE DATE,
	FOREIGN KEY (PRODUCT_NUMBER) REFERENCES TBL_PRODUCT(PRODUCT_NUMBER)
	-- FOREIGN KEY 설정으로 REFERENCES 외래키가 참조하는 테이블명(참조하는 컬럼명)
);











